name: Forge App Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy_staging:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Set up Forge CLI and lint code
        run: |
          npm install
          npm install -g @forge/cli
        env:
          CI: true

      - name: Deploy to Staging
        run: forge deploy -e staging --no-ansi --yes