name: Forge App Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Forge CLI
        run: npm install -g @forge/cli

      - name: Set Forge settings
        run: forge settings set usage-analytics true

      - name: Code linting
        run: |
          npm install
          forge lint
        env:
          CI: true