name: Forge App Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Forge CLI
        run: npm install -g @forge/cli

      - name: Authenticate with Jira
        run: forge login --email sarthak.handa@workato.com --token ATATT3xFfGF0-wrE4mLV9pM1nNM6TZytDtSzhhZC0862cYAAGhzZAQPE0_A-ex7Nn4mNUlq9N25Qg9yfNpV8uuPkrOIT9mShPNt5yKpx--Qs4RL4TtEkBzCY0L0xxRCw48laoeERK6Gg10WwuoQ3BmzBmuF66keIwQgPo-5zuJXPBSQdFzrUFas=29D25AE6

      - name: Install Dependencies
        run: npm install

      - name: Build and Package
        run: npm run build && forge package

      - name: Deploy to Jira
        run: forge deploy