name: forge cli

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Check Code linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install @forge/cli
        run: npm install --global @forge/cli

      - name: Set Forge usage-analytics
        run: forge settings set usage-analytics true

      - name: Deploy to Dev
        run: |
          forge deploy